FROM openjdk:8u131-jdk-alpine

MAINTAINER HARISH KUMAR SINHA "harish.k.sinha@gmail.com"

EXPOSE 8080

WORKDIR /usr/local/bin/

COPY micrSrvcInstOne-0.0.1-SNAPSHOT.jar micrsrvcone.jar

CMD ["java","-jar","micrsrvcone.jar"]